 CPP = g++

# OpenCV 2.4.9
CPPFLAGS = -L/home/adity/opencv-3.1.0/release/installed/lib \
       -I/home/adity/opencv-3.1.0/release/installed/include

all: test

test: code.cpp
    $(CPP) $(CPPFLAGS) $^ -o $@
